### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by flemton** [flemton/Final-Capstone-Frontend#13]
Dear reviewer, below is the link to our GitHub project

https://github.com/users/flemton/projects/2

Our group consisted of 3 members only and that's @sergio-usma, @SFarida and me (@flemton )

Screenshot 

<img width="1423" alt="Screenshot 2023-12-06 at 10 03 50 PM" src="https://github.com/flemton/Final-Capstone-Frontend/assets/36508436/7abc86fd-eb21-45c7-b851-8eae9750d398">

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
